definitions:
  base.BaseReq:
    properties:
      LogData:
        $ref: '#/definitions/base.LogData'
      ResponseData:
        $ref: '#/definitions/base.ResponseData'
    type: object
  base.LogData:
    properties:
      ExecutionTime:
        type: string
      HttpStatusCode:
        type: integer
      IP:
        type: string
      Route:
        type: string
    type: object
  base.ResponseData:
    properties:
      Response: {}
    type: object
  db.Company:
    properties:
      area:
        type: string
      cnpj:
        type: string
      id:
        type: integer
      name:
        type: string
      type:
        type: string
    type: object
  db.Sector:
    properties:
      company_id:
        type: integer
      content:
        items:
          type: integer
        type: array
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      number:
        type: string
    type: object
  db.SectorTest:
    properties:
      content:
        items:
          type: integer
        type: array
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      number:
        type: string
    type: object
  db.User:
    properties:
      company_id:
        type: integer
      email:
        type: string
      id:
        type: integer
      isLogged:
        type: boolean
      name:
        type: string
      password:
        type: string
      type:
        type: string
    type: object
  erros.InternalServerError:
    properties:
      BaseReq:
        $ref: '#/definitions/base.BaseReq'
      InternalServerError:
        $ref: '#/definitions/erros.Message'
      Response: {}
    type: object
  erros.Message:
    properties:
      message:
        type: string
    type: object
  interfaces.CompanyInput:
    properties:
      area:
        type: string
      cnpj:
        type: string
      company:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      type:
        type: string
    required:
    - area
    - cnpj
    - company
    - email
    - name
    - password
    - type
    type: object
  interfaces.NotConformInput:
    properties:
      Desc:
        type: string
      Legal:
        type: string
      Number:
        type: integer
      Recomended:
        type: string
      Tech:
        type: string
      Title:
        type: string
    type: object
  interfaces.SectorInput:
    properties:
      company_id:
        type: integer
      content:
        items:
          type: integer
        type: array
      description:
        type: string
      name:
        type: string
      number:
        type: string
    type: object
  interfaces.SectorInputTest:
    properties:
      content:
        items:
          type: integer
        type: array
      description:
        type: string
      name:
        type: string
      number:
        type: string
    type: object
  interfaces.UserInput:
    properties:
      companyName:
        type: string
      email:
        type: string
      name:
        type: string
      office:
        type: integer
      password:
        type: string
    required:
    - companyName
    - email
    - name
    - office
    - password
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: 3.138.100.192:8080
info:
  contact: {}
  description: This is a server for app.
  title: ConformeTec
  version: "1.0"
paths:
  /all-find-painel:
    get:
      consumes:
      - application/json
      description: Procurar um Painel existente
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.SectorTest'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Puxa todos os painels
      tags:
      - Test
  /api/test-token:
    post:
      consumes:
      - application/json
      description: Cria um toke para auth do usuario
      parameters:
      - default: Bearer <token>
        description: Token de autenticação
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'token make:'
          schema:
            type: string
      summary: Test Token
      tags:
      - Auth
  /create-painels-test:
    post:
      consumes:
      - application/json
      description: Criar um novo painel para uma empresa
      parameters:
      - description: Dados do campo a ser criado
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.SectorInputTest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.SectorTest'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Criar painel Test
      tags:
      - Test
  /create-sector:
    post:
      consumes:
      - application/json
      description: Criar um novo setor para uma empresa
      parameters:
      - description: Dados do campo a ser criado
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.SectorInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.Sector'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Criar setor
      tags:
      - Sector
  /find-company:
    get:
      consumes:
      - application/json
      description: Procurar uma companhia existente
      parameters:
      - description: Company do usuario
        in: header
        name: Company
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.Company'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Procurar uma companhia
      tags:
      - Company
  /find-sector:
    get:
      consumes:
      - application/json
      description: Procurar um setor especifico
      parameters:
      - description: Company do usuario
        in: header
        name: Company
        required: true
        type: string
      - description: Nome do setor
        in: header
        name: NameSector
        required: true
        type: string
      - description: Numero do setor
        in: header
        name: NumberSector
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.Sector'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Procurar setor
      tags:
      - Sector
  /find-user:
    get:
      consumes:
      - application/json
      description: Procurar um usuario existente
      parameters:
      - description: Rg do usuario
        in: header
        name: RG
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.User'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Procurar Usuario
      tags:
      - User
  /insert-nc:
    post:
      consumes:
      - application/json
      description: Insere um novo registro NC
      parameters:
      - description: Dados de entrada para inserção
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/interfaces.NotConformInput'
      produces:
      - application/json
      responses:
        "200":
          description: File uploaded successfully
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Inserir NC
      tags:
      - NC
  /loggout:
    put:
      consumes:
      - application/json
      description: Altera o modo de login para false
      parameters:
      - description: Email do usuario
        in: header
        name: Email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
        "500":
          description: Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Desconectar o usuario
      tags:
      - Login
  /login:
    put:
      consumes:
      - application/json
      description: Altera o modo de login para true
      parameters:
      - description: Email do usuario
        in: header
        name: Email
        required: true
        type: string
      - description: Senha do usuario
        in: header
        name: Password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
        "500":
          description: Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Conectar o usuario
      tags:
      - Login
  /pull-nc:
    get:
      consumes:
      - application/json
      description: Obtém registros NC com base nos parâmetros fornecidos
      parameters:
      - description: Email do usuario
        in: header
        name: Email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Obter NC
      tags:
      - NC
  /register:
    post:
      consumes:
      - application/json
      description: Criar um usuario a partir das novas infos
      parameters:
      - description: Dados do campo a ser criado
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.UserInput'
      - description: Tipo de usuário (Gerente da Planta 10, Profissional habilitado
          responsável 11, Responsável pelo PIE 12, Profissional autorizado 13)
        enum:
        - 10
        - 11
        - 12
        - 13
        in: header
        name: Office
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.User'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Criar um novo usuario
      tags:
      - User
  /register-company:
    post:
      consumes:
      - application/json
      description: Criar uma nova companhia
      parameters:
      - description: Dados do campo a ser criado
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/interfaces.CompanyInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.Company'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/erros.InternalServerError'
      summary: Criar uma nova companhia
      tags:
      - Company
  /token:
    get:
      consumes:
      - application/json
      description: Cria um toke para auth do usuario
      produces:
      - application/json
      responses:
        "200":
          description: 'token make:'
          schema:
            type: string
      summary: Criar token de auth
      tags:
      - Auth
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
